###

# use <leader>xr to trigger a request
GET https://api.ipify.org?format=json HTTP/1.1
Content-Type: application/json
Accept: application/json

###

GET https://httpbin.org/get HTTP/1.1
Content-Type: application/json
